version: '3'

services:
  sic-app:
    external_links:
      - postgres-example_sic-database_1
    ports:
      - "3000:3000"
    network_mode: bridge  
    volumes: 
    - ../sic-data/template_central:/home/AppData/template_central
    - ../sic-data/logs:/home/AppData/logs
    - ../sic-data/ruby_log:/home/AppData/ruby_log
    - ../sic-data/repositorios:/home/AppData/repositorios
    command: sh /run.sh
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APPNAME: sic
        AMBIENTE: homolog
        DB_NAME: sic
        DB_USER: postgres
        DB_PASS: postgres
        DB_HOST: postgres-example_sic-database_1
        PORTAL_DB_USER: postgres
        PORTAL_DB_PASS: postgres
        PORTAL_DB_HOST: postgres-example_sic-database_1