version: '3'

services:
  sic-database:
    # image: postgres:9.6
    ports:
      - "5499:5432"
    volumes: 
      - ../db_dumps:/database_dumps
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dpgeceti
    build:
      context: .
      dockerfile: Dockerfile 