# docker-compose.yml by Marcos Roberto
version: '3'
services:
  sic-database:
    ports:
      - "5499:5432"
    volumes: 
      - ../database_dumps:/database_dumps
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    build:
      context: .
      dockerfile: Dockerfile 