class AddAndamentoForcaTarefa < ActiveRecord::Migration
  def self.up
    ClassificacaoAndamento.create(:descricao => "Sem Providência", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Relaxamento", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Revogação de Preventiva", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Habeas Corpus", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Substituição de Cautelar", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Liberdade provisória", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Alegações Finais", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Resposta à Acusação", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Audiência de Justificação", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Recurso", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Retificação de soma de penas", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Calculo de pena", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Ofício", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Progressão de regime", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Livramento Condicional", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Defesa prévia", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Indulto", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Comutação de penas", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Remição de pena", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Prisão domiciliar", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Trabalho externo", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Extinção da punibilidade", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Unificação de penas(Continuidade delitiva)", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Comunicação interna", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Extinção de pena", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Readequação de regime", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Soma de penas", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Revisão Criminal", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Expedição de Guia", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Projeção de Benefício", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Outros", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Retificação de calculo", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Pedido de reconsideração", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Saída temporária", :tipo => "forca tarefa")
    ClassificacaoAndamento.create(:descricao => "Transferência de execução penal", :tipo => "forca tarefa")
  end
  def self.down
    ClassificacaoAndamento.delete_all(:descricao => "Sem Providência")
    ClassificacaoAndamento.delete_all(:descricao => "Relaxamento")
    ClassificacaoAndamento.delete_all(:descricao => "Revogação de Preventivaa")
    ClassificacaoAndamento.delete_all(:descricao => "Habeas Corpus")
    ClassificacaoAndamento.delete_all(:descricao => "Substituição de Cautelar")
    ClassificacaoAndamento.delete_all(:descricao => "Liberdade provisória")
    ClassificacaoAndamento.delete_all(:descricao => "Alegações Finais")
    ClassificacaoAndamento.delete_all(:descricao => "Resposta à Acusação")
    ClassificacaoAndamento.delete_all(:descricao => "Audiência de Justificação")
    ClassificacaoAndamento.delete_all(:descricao => "Recurso")
    ClassificacaoAndamento.delete_all(:descricao => "Retificação de soma de penas")
    ClassificacaoAndamento.delete_all(:descricao => "Calculo de pena")
    ClassificacaoAndamento.delete_all(:descricao => "Ofício")
    ClassificacaoAndamento.delete_all(:descricao => "Progressão de regime")
    ClassificacaoAndamento.delete_all(:descricao => "Livramento Condicional")
    ClassificacaoAndamento.delete_all(:descricao => "Defesa prévia")
    ClassificacaoAndamento.delete_all(:descricao => "Indulto")
    ClassificacaoAndamento.delete_all(:descricao => "Comutação de penas")
    ClassificacaoAndamento.delete_all(:descricao => "Remição de pena")
    ClassificacaoAndamento.delete_all(:descricao => "Prisão domiciliar")
    ClassificacaoAndamento.delete_all(:descricao => "Trabalho externo")
    ClassificacaoAndamento.delete_all(:descricao => "Extinção da punibilidade")
    ClassificacaoAndamento.delete_all(:descricao => "Unificação de penas(Continuidade delitiva)")
    ClassificacaoAndamento.delete_all(:descricao => "Comunicação interna")
    ClassificacaoAndamento.delete_all(:descricao => "Extinção de pena")
    ClassificacaoAndamento.delete_all(:descricao => "Readequação de regime")
    ClassificacaoAndamento.delete_all(:descricao => "Soma de penas")
    ClassificacaoAndamento.delete_all(:descricao => "Revisão Criminal")
    ClassificacaoAndamento.delete_all(:descricao => "Expedição de Guia")
    ClassificacaoAndamento.delete_all(:descricao => "Projeção de Benefício")
    ClassificacaoAndamento.delete_all(:descricao => "Outros")
    ClassificacaoAndamento.delete_all(:descricao => "Retificação de calculo")
    ClassificacaoAndamento.delete_all(:descricao => "Pedido de reconsideração")
    ClassificacaoAndamento.delete_all(:descricao => "Saída temporária")
    ClassificacaoAndamento.delete_all(:descricao => "Transferência de execução penal")
  end
end
