class ImportClassificacao < ActiveRecord::Migration
  def self.up
    ClassificacaoAndamento.create(:descricao => "Análise de Prontuário/Procedimento")
    ClassificacaoAndamento.create(:descricao => "Apresentação Indiciado/Representado")
    ClassificacaoAndamento.create(:descricao => "Atendimento")
    ClassificacaoAndamento.create(:descricao => "Atividade Extras/Outros")
    ClassificacaoAndamento.create(:descricao => "Atividades de Cartório")
    ClassificacaoAndamento.create(:descricao => "Atividades de Coordenação")
    ClassificacaoAndamento.create(:descricao => "Audiencia Extrajudicial")
    ClassificacaoAndamento.create(:descricao => "Audiências Judiciais")
    ClassificacaoAndamento.create(:descricao => "Ciência de Ofícios/Documentos Recebidos")
    ClassificacaoAndamento.create(:descricao => "Ciências de Atos Processuais")
    ClassificacaoAndamento.create(:descricao => "Eventos")
    ClassificacaoAndamento.create(:descricao => "Livros com Pertinência Temática")
    ClassificacaoAndamento.create(:descricao => "Notificações")
    ClassificacaoAndamento.create(:descricao => "Oficios/Requisições")
    ClassificacaoAndamento.create(:descricao => "Participação em Curso")
    ClassificacaoAndamento.create(:descricao => "Petição Geral")
    ClassificacaoAndamento.create(:descricao => "Petição Geral em Massa")
    ClassificacaoAndamento.create(:descricao => "Petição Inicial")
    ClassificacaoAndamento.create(:descricao => "Petição Intitulado")
    ClassificacaoAndamento.create(:descricao => "Procedimentos Administrativos")
    ClassificacaoAndamento.create(:descricao => "Publicação de Artigos")
    ClassificacaoAndamento.create(:descricao => "Recurso")
    ClassificacaoAndamento.create(:descricao => "Requerimentos/Declarações")
    ClassificacaoAndamento.create(:descricao => "Sessões de Júri")
    ClassificacaoAndamento.create(:descricao => "Visitas/Inspeções/Pericia")
    ClassificacaoAndamento.create(:descricao => "Vistas dos Autos")
  end
  def self.down
    ClassificacaoAndamento.delete_all(:descricao => "Análise de Prontuário/Procedimento")
    ClassificacaoAndamento.delete_all(:descricao => "Apresentação Indiciado/Representado")
    ClassificacaoAndamento.delete_all(:descricao => "Atendimento")
    ClassificacaoAndamento.delete_all(:descricao => "Atividade Extras/Outros")
    ClassificacaoAndamento.delete_all(:descricao => "Atividades de Cartório")
    ClassificacaoAndamento.delete_all(:descricao => "Atividades de Coordenação")
    ClassificacaoAndamento.delete_all(:descricao => "Audiencia Extrajudicial")
    ClassificacaoAndamento.delete_all(:descricao => "Audiências Judiciais")
    ClassificacaoAndamento.delete_all(:descricao => "Ciência de Ofícios/Documentos Recebidos")
    ClassificacaoAndamento.delete_all(:descricao => "Ciências de Atos Processuais")
    ClassificacaoAndamento.delete_all(:descricao => "Eventos")
    ClassificacaoAndamento.delete_all(:descricao => "Livros com Pertinência Temática")
    ClassificacaoAndamento.delete_all(:descricao => "Notificações")
    ClassificacaoAndamento.delete_all(:descricao => "Oficios/Requisições")
    ClassificacaoAndamento.delete_all(:descricao => "Participação em Curso")
    ClassificacaoAndamento.delete_all(:descricao => "Petição Geral")
    ClassificacaoAndamento.delete_all(:descricao => "Petição Geral em Massa")
    ClassificacaoAndamento.delete_all(:descricao => "Petição Inicial")
    ClassificacaoAndamento.delete_all(:descricao => "Petição Intitulado")
    ClassificacaoAndamento.delete_all(:descricao => "Procedimentos Administrativos")
    ClassificacaoAndamento.delete_all(:descricao => "Publicação de Artigos")
    ClassificacaoAndamento.delete_all(:descricao => "Recurso")
    ClassificacaoAndamento.delete_all(:descricao => "Requerimentos/Declarações")
    ClassificacaoAndamento.delete_all(:descricao => "Sessões de Júri")
    ClassificacaoAndamento.delete_all(:descricao => "Visitas/Inspeções/Pericia")
    ClassificacaoAndamento.delete_all(:descricao => "Vistas dos Autos")
  end
end
