kind: PersistentVolume
apiVersion: v1
metadata:
  name: docker-registry-pv
  namespace: docker-registry-srv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: k8s-nfs1
    path: "/home/docker-registry-data"