kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-registry-pvc
  namespace: docker-registry-srv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 30Gi