kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sic-homolog-pvc
  namespace: sic-homolog
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi