kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitlab-pv
  namespace: gitlab-srv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: k8s-nfs1
    path: "/home/gitlab-data"